version: 2

jobs:
  build: # name of your job
    docker:
      - image: circleci/node:latest
    resource_class: windows.medium
    steps:
      # Commands are run in a Windows virtual machine environment
        - checkout
        - run: Write-Host 'Hello, Windows'
